services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "8092:27017"     # Host 8092 → Mongo 27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../app/backend
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/electromart
      - FRONTEND_ORIGIN=http://localhost:8090
    ports:
      - "8091:5000"      # Host 8091 → Backend 5000

  frontend:
    build:
      context: ../app/frontend
      args:
        REACT_APP_API_URL: http://localhost:8091  # frontend → backend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8090:80"         # Host 8090 → Nginx 80 (frontend)

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8093:9090"       # Host 8093 → Prometheus 9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8094:3000"       # Host 8094 → Grafana 3000

volumes:
  mongo_data:
